name: Weekly Gugles Mission Tracker
on:
  schedule:
    - cron: "1 15 * * 0"
jobs:
  run_gugles_mission_tracker:
    runs-on: ubuntu-latest
    env:
      CREW_NUM: ${{ secrets.CREW_NUM }}
      GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
      GSPREAD_CREDENTIAL_KEY: ${{ secrets.GSPREAD_CREDENTIAL_KEY }}
      TEST_CATEGORY_ID: ${{ secrets.TEST_CATEGORY_ID }}
      CATEGORIES: ${{ secrets.CATEGORIES }}
      APOLOGY_CATEGORY: ${{ secrets.APOLOGY_CATEGORY }}
      ANNOUNCEMENT_CATEGORY_ID: ${{ secrets.ANNOUNCEMENT_CATEGORY_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run gugles_mission_tracker
        run: |
          poetry run mission_tracker report
        env:
          CREW_NUM: ${{ env.CREW_NUM }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GSPREAD_CREDENTIAL_KEY: ${{ env.GSPREAD_CREDENTIAL_KEY }}
          TEST_CATEGORY_ID: ${{ env.TEST_CATEGORY_ID }}
          CATEGORIES: ${{ env.CATEGORIES }}
          APOLOGY_CATEGORY: ${{ env.APOLOGY_CATEGORY }}
          ANNOUNCEMENT_CATEGORY_ID: ${{ env.ANNOUNCEMENT_CATEGORY_ID }}
